<?php
/**
 * SayNoMore - mail.php
 * Created by Leproide - https://github.com/Leproide/SayNoMore
 *
 * Distributed under GNU GPL v2.
 * No warranty provided.
 *
 * Client SMTP nativo (niente PHPMailer, niente Composer) per l'invio delle
 * notifiche email opzionali generate da view.php quando un segreto viene
 * letto o distrutto per troppi tentativi errati.
 *
 * Supporta:
 *  - SSL implicito (porta 465, secure='ssl')
 *  - STARTTLS      (porta 587, secure='tls')
 *  - Plaintext     (porta 25,  secure='')
 *  - Autenticazione AUTH LOGIN (utente/password base64)
 *  - Messaggi multipart/alternative (plain + HTML)
 *
 * Filosofia: i fallimenti di invio NON devono mai impattare il flusso
 * principale. Tutti gli errori vengono catturati e loggati via error_log,
 * mai mostrati all'utente.
 */

require_once __DIR__ . '/lang.php';

/**
 * Carica e memorizza in cache la configurazione SMTP da mailconfig.php.
 * Restituisce ['enabled' => false] se il file e' assente o malformato.
 */
function snm_mail_config(): array {
    static $cfg = null;
    if ($cfg !== null) return $cfg;

    $path = __DIR__ . '/mailconfig.php';
    if (!is_file($path)) {
        return $cfg = ['enabled' => false];
    }
    $loaded = @include $path;
    if (!is_array($loaded)) {
        return $cfg = ['enabled' => false];
    }
    return $cfg = $loaded;
}

/**
 * Helper: la funzionalita' notifiche e' attiva?
 */
function snm_mail_enabled(): bool {
    $cfg = snm_mail_config();
    return !empty($cfg['enabled']);
}

/**
 * Costruisce e invia una notifica per un evento sul segreto.
 *
 * @param string $to       Indirizzo destinatario (gia' validato dal chiamante)
 * @param string $tokenId  Identificatore breve da mostrare (es. primi 8 char del token)
 * @param string $event    'read' oppure 'destroyed'
 * @param string $lang     'it' o 'en' (lingua scelta alla creazione del segreto)
 * @return bool true se l'invio e' stato accettato dal server SMTP
 */
function snm_send_notification(string $to, string $tokenId, string $event, string $lang = 'en'): bool {
    if (!snm_mail_enabled()) return false;
    if (!filter_var($to, FILTER_VALIDATE_EMAIL)) return false;

    // Sanifica id (solo hex), max 32 char come il token completo
    $tokenId = substr(preg_replace('/[^a-f0-9]/i', '', $tokenId), 0, 32);
    if ($tokenId === '') return false;

    $when   = date('Y-m-d H:i:s T');
    $lang   = ($lang === 'it') ? 'it' : 'en';
    $isRead = ($event === 'read');

    // --- Soggetto + corpo testuale + frammenti per il corpo HTML ---
    if ($lang === 'it') {
        $subject  = $isRead
            ? "[SayNoMore] Segreto {$tokenId} letto"
            : "[SayNoMore] Segreto {$tokenId} distrutto";
        $bodyText = $isRead
            ? "Il segreto {$tokenId} è stato aperto in data {$when}.\r\n"
            : "Il segreto {$tokenId} è stato distrutto in data {$when} dopo troppi tentativi errati.\r\n";
        $heading   = $isRead ? 'Segreto letto' : 'Segreto distrutto';
        $intro     = $isRead
            ? "Il segreto <strong>{$tokenId}</strong> è stato aperto correttamente."
            : "Il segreto <strong>{$tokenId}</strong> è stato distrutto dopo troppi tentativi errati.";
        $labelId   = 'ID segreto';
        $labelWhen = 'Data e ora';
        $footer    = 'Notifica automatica generata da SayNoMore.';
    } else {
        $subject  = $isRead
            ? "[SayNoMore] Secret {$tokenId} read"
            : "[SayNoMore] Secret {$tokenId} destroyed";
        $bodyText = $isRead
            ? "Secret {$tokenId} was opened on {$when}.\r\n"
            : "Secret {$tokenId} was destroyed on {$when} after too many failed attempts.\r\n";
        $heading   = $isRead ? 'Secret read' : 'Secret destroyed';
        $intro     = $isRead
            ? "Secret <strong>{$tokenId}</strong> has been successfully opened."
            : "Secret <strong>{$tokenId}</strong> has been destroyed after too many failed attempts.";
        $labelId   = 'Secret ID';
        $labelWhen = 'Date and time';
        $footer    = 'Automatic notification generated by SayNoMore.';
    }

    // Accento coerente con la palette CSS del sito: blu per "read",
    // rosso (error-color) per "destroyed".
    $accent = $isRead ? '#4A76D9' : '#ff6b6b';

    // Corpo HTML: layout table-based (compatibile con tutti i client email),
    // colori in linea (gli MUA spesso strippano <style>), nessuna risorsa
    // esterna, tutte le stringhe gia' escaped o costanti.
    $idEsc      = htmlspecialchars($tokenId,   ENT_QUOTES, 'UTF-8');
    $whenEsc    = htmlspecialchars($when,      ENT_QUOTES, 'UTF-8');
    $headingEsc = htmlspecialchars($heading,   ENT_QUOTES, 'UTF-8');
    $labelIdEsc = htmlspecialchars($labelId,   ENT_QUOTES, 'UTF-8');
    $labelWhEsc = htmlspecialchars($labelWhen, ENT_QUOTES, 'UTF-8');
    $footerEsc  = htmlspecialchars($footer,    ENT_QUOTES, 'UTF-8');

    $bodyHtml =
        '<!DOCTYPE html><html><body style="margin:0;padding:0;background:#1a1d2e;font-family:Arial,Helvetica,sans-serif;color:#E5E9F0;">'
      . '<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#1a1d2e;padding:32px 0;">'
      .   '<tr><td align="center">'
      .     '<table width="520" cellpadding="0" cellspacing="0" border="0" style="background:#2A2F4A;border-radius:12px;border:1px solid #3B3F5C;">'
      .       '<tr><td style="padding:24px 28px;border-bottom:1px solid #3B3F5C;">'
      .         '<div style="font-size:22px;font-weight:bold;color:#E5E9F0;letter-spacing:0.5px;">SayNoMore</div>'
      .         '<div style="font-size:13px;color:#A5A8C5;margin-top:4px;">' . $headingEsc . '</div>'
      .       '</td></tr>'
      .       '<tr><td style="padding:28px;">'
      .         '<div style="display:inline-block;padding:6px 12px;border-radius:6px;background:' . $accent . ';color:#ffffff;font-size:11px;font-weight:bold;letter-spacing:1px;text-transform:uppercase;">'
      .           $headingEsc
      .         '</div>'
      .         '<p style="margin:20px 0 0 0;font-size:15px;line-height:1.6;color:#E5E9F0;">' . $intro . '</p>'
      .         '<table cellpadding="0" cellspacing="0" border="0" style="margin-top:24px;width:100%;border-collapse:collapse;">'
      .           '<tr>'
      .             '<td style="padding:12px 0;font-size:13px;color:#A5A8C5;width:38%;border-top:1px solid #3B3F5C;">' . $labelIdEsc . '</td>'
      .             '<td style="padding:12px 0;font-size:13px;color:#E5E9F0;font-family:Consolas,Menlo,monospace;border-top:1px solid #3B3F5C;">' . $idEsc . '</td>'
      .           '</tr>'
      .           '<tr>'
      .             '<td style="padding:12px 0;font-size:13px;color:#A5A8C5;border-top:1px solid #3B3F5C;">' . $labelWhEsc . '</td>'
      .             '<td style="padding:12px 0;font-size:13px;color:#E5E9F0;border-top:1px solid #3B3F5C;">' . $whenEsc . '</td>'
      .           '</tr>'
      .         '</table>'
      .       '</td></tr>'
      .       '<tr><td style="padding:18px 28px;border-top:1px solid #3B3F5C;font-size:11px;color:#6e7396;text-align:center;">'
      .         $footerEsc
      .       '</td></tr>'
      .     '</table>'
      .   '</td></tr>'
      . '</table>'
      . '</body></html>';

    try {
        return snm_smtp_send(snm_mail_config(), $to, $subject, $bodyText, $bodyHtml);
    } catch (\Throwable $e) {
        // Fallimento silenzioso lato utente: solo log lato server.
        error_log('[SayNoMore] mail send failed: ' . $e->getMessage());
        return false;
    }
}

/**
 * Variante "deferred" di snm_send_notification: posticipa l'invio dopo
 * che la response e' stata consegnata al client. Questo evita che l'utente
 * resti in attesa per tutto il timeout SMTP (fino a 10s di default) prima
 * di vedere il segreto o la pagina di errore "Troppi tentativi".
 *
 * Strategia:
 *  - register_shutdown_function() esegue la callback dopo la fine dello script
 *  - dentro la callback, se siamo su PHP-FPM chiamiamo fastcgi_finish_request()
 *    che chiude la connessione TCP al client e libera il browser
 *  - su mod_php (Apache embedded) fallback best-effort: flush + ignore_user_abort
 *
 * Risultato: l'utente vede la pagina immediatamente, la mail parte in
 * background. Anche un timing-attack che misurasse "ha notifiche attive?"
 * dal tempo di risposta non riceve informazione utile.
 *
 * @param string $to       Indirizzo destinatario
 * @param string $tokenId  Identificatore breve del segreto
 * @param string $event    'read' | 'destroyed'
 * @param string $lang     'it' | 'en'
 */
function snm_send_notification_deferred(string $to, string $tokenId, string $event, string $lang = 'en'): void {
    if (!snm_mail_enabled()) return;
    if (!filter_var($to, FILTER_VALIDATE_EMAIL)) return;

    register_shutdown_function(static function () use ($to, $tokenId, $event, $lang) {
        // Rilascia il client prima di parlare con l'SMTP
        if (function_exists('fastcgi_finish_request')) {
            @fastcgi_finish_request();
        } else {
            // mod_php / SAPI senza fastcgi_finish_request: best effort
            @ignore_user_abort(true);
            if (session_status() === PHP_SESSION_ACTIVE) {
                @session_write_close();
            }
            while (ob_get_level() > 0) {
                @ob_end_flush();
            }
            @flush();
        }
        snm_send_notification($to, $tokenId, $event, $lang);
    });
}

/**
 * Invio SMTP via socket. Implementazione sincrona, single-shot.
 * Lancia RuntimeException su qualsiasi errore (catturata dal chiamante).
 */
function snm_smtp_send(array $cfg, string $to, string $subject, string $bodyText, string $bodyHtml): bool {
    $host    = (string)($cfg['host']      ?? '');
    $port    = (int)   ($cfg['port']      ?? 587);
    $secure  = strtolower((string)($cfg['secure']    ?? ''));
    $user    = (string)($cfg['username']  ?? '');
    $pass    = (string)($cfg['password']  ?? '');
    $from    = (string)($cfg['from']      ?? $user);
    $fromN   = (string)($cfg['from_name'] ?? 'SayNoMore');
    $timeout = (int)   ($cfg['timeout']   ?? 10);

    if ($host === '' || $port <= 0 || $from === '') {
        throw new \RuntimeException('SMTP config incomplete');
    }

    // --- Defense in depth contro SMTP command injection ---
    // $to e' gia' validato con FILTER_VALIDATE_EMAIL (che rifiuta CRLF) sia
    // in index.php sia in snm_send_notification(). $from arriva dalla config
    // statica, sotto controllo admin. Aggiungiamo comunque uno strip esplicito
    // dei CRLF prima di scriverli nei comandi MAIL FROM / RCPT TO per evitare
    // SMTP smuggling se in futuro qualcuno aggira una delle validazioni.
    $to   = str_replace(["\r", "\n", "\0"], '', $to);
    $from = str_replace(["\r", "\n", "\0"], '', $from);

    // SSL implicito = wrapper ssl:// gia' al connect.
    // STARTTLS    = connessione plaintext, upgrade dopo EHLO.
    $remote = ($secure === 'ssl' ? 'ssl://' : '') . $host . ':' . $port;

    $errno = 0;
    $errstr = '';
    $sock = @stream_socket_client($remote, $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT);
    if (!$sock) {
        throw new \RuntimeException("SMTP connect failed: {$errstr} ({$errno})");
    }
    stream_set_timeout($sock, $timeout);

    // Lettore di risposte SMTP multi-line: l'ultima riga ha lo space dopo il
    // codice numerico (es. "250 OK"), le precedenti hanno il dash ("250-EHLO").
    $read = static function () use ($sock) {
        $data = '';
        while (!feof($sock)) {
            $line = fgets($sock, 1024);
            if ($line === false) break;
            $data .= $line;
            if (isset($line[3]) && $line[3] === ' ') break;
        }
        return $data;
    };
    $write = static function (string $cmd) use ($sock) {
        fwrite($sock, $cmd . "\r\n");
    };
    $expect = static function (string $resp, string $code) {
        if (substr($resp, 0, 3) !== $code) {
            throw new \RuntimeException('SMTP unexpected response: ' . trim($resp));
        }
    };

    $resp = $read();
    $expect($resp, '220');

    $hostname = gethostname() ?: 'localhost';
    $write('EHLO ' . $hostname);
    $expect($read(), '250');

    if ($secure === 'tls') {
        $write('STARTTLS');
        $expect($read(), '220');
        // Crypto upgrade. Accettiamo TLS 1.2 e successivi (la costante
        // STREAM_CRYPTO_METHOD_TLS_CLIENT include automaticamente le versioni
        // moderne supportate dall'openssl in uso).
        if (!stream_socket_enable_crypto($sock, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
            fclose($sock);
            throw new \RuntimeException('STARTTLS upgrade failed');
        }
        // EHLO va ripetuto dopo STARTTLS (RFC 3207).
        $write('EHLO ' . $hostname);
        $expect($read(), '250');
    }

    if ($user !== '' && $pass !== '') {
        $write('AUTH LOGIN');
        $expect($read(), '334');
        $write(base64_encode($user));
        $expect($read(), '334');
        $write(base64_encode($pass));
        $expect($read(), '235');
    }

    $write('MAIL FROM:<' . $from . '>');
    $expect($read(), '250');
    $write('RCPT TO:<' . $to . '>');
    // 250 = OK, 251 = forward (entrambi accettabili)
    $resp = $read();
    if (substr($resp, 0, 3) !== '250' && substr($resp, 0, 3) !== '251') {
        throw new \RuntimeException('SMTP RCPT rejected: ' . trim($resp));
    }
    $write('DATA');
    $expect($read(), '354');

    // Boundary random per multipart/alternative
    $boundary = 'snm_' . bin2hex(random_bytes(12));
    $date     = date('r');
    $hostSan  = preg_replace('/[^a-z0-9.\-]/i', '', $hostname) ?: 'localhost';
    $msgId    = '<' . bin2hex(random_bytes(8)) . '@' . $hostSan . '>';

    // Header From con nome encoded in RFC 2047 (UTF-8 base64) per safety.
    $fromEnc = '=?UTF-8?B?' . base64_encode($fromN) . '?=';
    $subjEnc = '=?UTF-8?B?' . base64_encode($subject) . '?=';

    $headers   = [];
    $headers[] = 'Date: ' . $date;
    $headers[] = 'Message-ID: ' . $msgId;
    $headers[] = 'From: ' . $fromEnc . ' <' . $from . '>';
    $headers[] = 'To: <' . $to . '>';
    $headers[] = 'Subject: ' . $subjEnc;
    $headers[] = 'MIME-Version: 1.0';
    $headers[] = 'Content-Type: multipart/alternative; boundary="' . $boundary . '"';
    $headers[] = 'X-Mailer: SayNoMore';

    $body  = '';
    $body .= '--' . $boundary . "\r\n";
    $body .= 'Content-Type: text/plain; charset=UTF-8' . "\r\n";
    $body .= 'Content-Transfer-Encoding: 8bit' . "\r\n\r\n";
    $body .= $bodyText . "\r\n";
    $body .= '--' . $boundary . "\r\n";
    $body .= 'Content-Type: text/html; charset=UTF-8' . "\r\n";
    $body .= 'Content-Transfer-Encoding: 8bit' . "\r\n\r\n";
    $body .= $bodyHtml . "\r\n";
    $body .= '--' . $boundary . '--' . "\r\n";

    $data = implode("\r\n", $headers) . "\r\n\r\n" . $body;
    // Dot-stuffing: ogni riga che inizia con "." va raddoppiata (RFC 5321 §4.5.2)
    // perche' la singola "." su una riga marca la fine del DATA block.
    $data = preg_replace('/^\./m', '..', $data);

    fwrite($sock, $data . "\r\n.\r\n");
    $expect($read(), '250');

    $write('QUIT');
    @fread($sock, 1024);
    fclose($sock);
    return true;
}
